version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "npm dependency"
    ignore:
      - dependency-name: "npm"
        update-types: [ "version-update:semver-patch" ]
    labels:
      - "dependency"
