export const languageMap: Map<string, string> = new Map();

languageMap.set("af-ZA", "Afrikaans (South Africa)");
languageMap.set("am-ET", "Amharic (Ethiopia)");
languageMap.set("ar-AE", "Arabic (United Arab Emirates)");
languageMap.set("ar-SA", "Arabic (Saudi Arabia)");
languageMap.set("az-AZ", "Azerbaijani (Azerbaijan)");
languageMap.set("be-BY", "Belarusian (Belarus)");
languageMap.set("bg-BG", "Bulgarian (Bulgaria)");
languageMap.set("bn-BD", "Bengali (Bangladesh)");
languageMap.set("bs-BA", "Bosnian (Bosnia and Herzegovina)");
languageMap.set("ca-ES", "Catalan (Spain)");
languageMap.set("cs-CZ", "Czech (Czech Republic)");
languageMap.set("cy-GB", "Welsh (United Kingdom)");
languageMap.set("da-DK", "Danish (Denmark)");
languageMap.set("de-AT", "German (Austria)");
languageMap.set("de-CH", "German (Switzerland)");
languageMap.set("de-DE", "German (Germany)");
languageMap.set("el-GR", "Greek (Greece)");
languageMap.set("en-AU", "English (Australia)");
languageMap.set("en-CA", "English (Canada)");
languageMap.set("en-GB", "English (United Kingdom)");
languageMap.set("en-IE", "English (Ireland)");
languageMap.set("en-IN", "English (India)");
languageMap.set("en-NZ", "English (New Zealand)");
languageMap.set("en-US", "English (United States)");
languageMap.set("es-AR", "Spanish (Argentina)");
languageMap.set("es-CL", "Spanish (Chile)");
languageMap.set("es-CO", "Spanish (Colombia)");
languageMap.set("es-ES", "Spanish (Spain)");
languageMap.set("es-MX", "Spanish (Mexico)");
languageMap.set("es-PE", "Spanish (Peru)");
languageMap.set("et-EE", "Estonian (Estonia)");
languageMap.set("eu-ES", "Basque (Spain)");
languageMap.set("fa-IR", "Persian (Iran)");
languageMap.set("fi-FI", "Finnish (Finland)");
languageMap.set("fr-BE", "French (Belgium)");
languageMap.set("fr-CA", "French (Canada)");
languageMap.set("fr-CH", "French (Switzerland)");
languageMap.set("fr-FR", "French (France)");
languageMap.set("ga-IE", "Irish (Ireland)");
languageMap.set("gl-ES", "Galician (Spain)");
languageMap.set("gu-IN", "Gujarati (India)");
languageMap.set("he-IL", "Hebrew (Israel)");
languageMap.set("hi-IN", "Hindi (India)");
languageMap.set("hr-HR", "Croatian (Croatia)");
languageMap.set("hu-HU", "Hungarian (Hungary)");
languageMap.set("hy-AM", "Armenian (Armenia)");
languageMap.set("id-ID", "Indonesian (Indonesia)");
languageMap.set("is-IS", "Icelandic (Iceland)");
languageMap.set("it-CH", "Italian (Switzerland)");
languageMap.set("it-IT", "Italian (Italy)");
languageMap.set("ja-JP", "Japanese (Japan)");
languageMap.set("jv-ID", "Javanese (Indonesia)");
languageMap.set("ka-GE", "Georgian (Georgia)");
languageMap.set("kk-KZ", "Kazakh (Kazakhstan)");
languageMap.set("km-KH", "Khmer (Cambodia)");
languageMap.set("kn-IN", "Kannada (India)");
languageMap.set("ko-KR", "Korean (South Korea)");
languageMap.set("ku-TR", "Kurdish (Turkey)");
languageMap.set("ky-KG", "Kyrgyz (Kyrgyzstan)");
languageMap.set("la-VA", "Latin (Vatican)");
languageMap.set("lb-LU", "Luxembourgish (Luxembourg)");
languageMap.set("lo-LA", "Lao (Laos)");
languageMap.set("lt-LT", "Lithuanian (Lithuania)");
languageMap.set("lv-LV", "Latvian (Latvia)");
languageMap.set("mg-MG", "Malagasy (Madagascar)");
languageMap.set("mk-MK", "Macedonian (North Macedonia)");
languageMap.set("ml-IN", "Malayalam (India)");
languageMap.set("mn-MN", "Mongolian (Mongolia)");
languageMap.set("mr-IN", "Marathi (India)");
languageMap.set("ms-MY", "Malay (Malaysia)");
languageMap.set("mt-MT", "Maltese (Malta)");
languageMap.set("my-MM", "Burmese (Myanmar)");
languageMap.set("nb-NO", "Norwegian Bokmål (Norway)");
languageMap.set("ne-NP", "Nepali (Nepal)");
languageMap.set("nl-BE", "Dutch (Belgium)");
languageMap.set("nl-NL", "Dutch (Netherlands)");
languageMap.set("nn-NO", "Norwegian Nynorsk (Norway)");
languageMap.set("or-IN", "Odia (India)");
languageMap.set("pa-IN", "Punjabi (India)");
languageMap.set("pl-PL", "Polish (Poland)");
languageMap.set("ps-AF", "Pashto (Afghanistan)");
languageMap.set("pt-BR", "Portuguese (Brazil)");
languageMap.set("pt-PT", "Portuguese (Portugal)");
languageMap.set("ro-RO", "Romanian (Romania)");
languageMap.set("ru-RU", "Russian (Russia)");
languageMap.set("si-LK", "Sinhala (Sri Lanka)");
languageMap.set("sk-SK", "Slovak (Slovakia)");
languageMap.set("sl-SI", "Slovenian (Slovenia)");
languageMap.set("sq-AL", "Albanian (Albania)");
languageMap.set("sr-RS", "Serbian (Serbia)");
languageMap.set("sv-SE", "Swedish (Sweden)");
languageMap.set("sw-KE", "Swahili (Kenya)");
languageMap.set("ta-IN", "Tamil (India)");
languageMap.set("te-IN", "Telugu (India)");
languageMap.set("th-TH", "Thai (Thailand)");
languageMap.set("tl-PH", "Tagalog (Philippines)");
languageMap.set("tr-TR", "Turkish (Turkey)");
languageMap.set("ug-CN", "Uyghur (China)");
languageMap.set("uk-UA", "Ukrainian (Ukraine)");
languageMap.set("ur-PK", "Urdu (Pakistan)");
languageMap.set("uz-UZ", "Uzbek (Uzbekistan)");
languageMap.set("vi-VN", "Vietnamese (Vietnam)");
languageMap.set("zh-CN", "Chinese (China)");
languageMap.set("zh-HK", "Chinese (Hong Kong)");
languageMap.set("zh-TW", "Chinese (Taiwan)");
languageMap.set("zu-ZA", "Zulu (South Africa)");