export const languageAndRegions: LanguageAndRegion[] = [
    {languageAndRegionCode: "af-ZA", regionCode: "ZA", languageAndRegion: "Afrikaans (South Africa)", region: "South Africa"},
    {languageAndRegionCode: "am-ET", regionCode: "ET", languageAndRegion: "Amharic (Ethiopia)", region: "Ethiopia"},
    {languageAndRegionCode: "ar-AE", regionCode: "AE", languageAndRegion: "Arabic (United Arab Emirates)", region: "United Arab Emirates"},
    {languageAndRegionCode: "ar-SA", regionCode: "SA", languageAndRegion: "Arabic (Saudi Arabia)", region: "Saudi Arabia"},
    {languageAndRegionCode: "az-AZ", regionCode: "AZ", languageAndRegion: "Azerbaijani (Azerbaijan)", region: "Azerbaijan"},
    {languageAndRegionCode: "be-BY", regionCode: "BY", languageAndRegion: "Belarusian (Belarus)", region: "Belarus"},
    {languageAndRegionCode: "bg-BG", regionCode: "BG", languageAndRegion: "Bulgarian (Bulgaria)", region: "Bulgaria"},
    {languageAndRegionCode: "bn-BD", regionCode: "BD", languageAndRegion: "Bengali (Bangladesh)", region: "Bangladesh"},
    {languageAndRegionCode: "bs-BA", regionCode: "BA", languageAndRegion: "Bosnian (Bosnia and Herzegovina)", region: "Bosnia and Herzegovina"},
    {languageAndRegionCode: "ca-ES", regionCode: "ES", languageAndRegion: "Catalan (Spain)", region: "Spain"},
    {languageAndRegionCode: "cs-CZ", regionCode: "CZ", languageAndRegion: "Czech (Czech Republic)", region: "Czech Republic"},
    {languageAndRegionCode: "cy-GB", regionCode: "GB", languageAndRegion: "Welsh (United Kingdom)", region: "United Kingdom"},
    {languageAndRegionCode: "da-DK", regionCode: "DK", languageAndRegion: "Danish (Denmark)", region: "Denmark"},
    {languageAndRegionCode: "de-AT", regionCode: "AT", languageAndRegion: "German (Austria)", region: "Austria"},
    {languageAndRegionCode: "de-CH", regionCode: "CH", languageAndRegion: "German (Switzerland)", region: "Switzerland"},
    {languageAndRegionCode: "de-DE", regionCode: "DE", languageAndRegion: "German (Germany)", region: "Germany"},
    {languageAndRegionCode: "el-GR", regionCode: "GR", languageAndRegion: "Greek (Greece)", region: "Greece"},
    {languageAndRegionCode: "en-AU", regionCode: "AU", languageAndRegion: "English (Australia)", region: "Australia"},
    {languageAndRegionCode: "en-CA", regionCode: "CA", languageAndRegion: "English (Canada)", region: "Canada"},
    {languageAndRegionCode: "en-GB", regionCode: "GB", languageAndRegion: "English (United Kingdom)", region: "United Kingdom"},
    {languageAndRegionCode: "en-IE", regionCode: "IE", languageAndRegion: "English (Ireland)", region: "Ireland"},
    {languageAndRegionCode: "en-IN", regionCode: "IN", languageAndRegion: "English (India)", region: "India"},
    {languageAndRegionCode: "en-NZ", regionCode: "NZ", languageAndRegion: "English (New Zealand)", region: "New Zealand"},
    {languageAndRegionCode: "en-US", regionCode: "US", languageAndRegion: "English (United States)", region: "United States"},
    {languageAndRegionCode: "es-AR", regionCode: "AR", languageAndRegion: "Spanish (Argentina)", region: "Argentina"},
    {languageAndRegionCode: "es-CL", regionCode: "CL", languageAndRegion: "Spanish (Chile)", region: "Chile"},
    {languageAndRegionCode: "es-CO", regionCode: "CO", languageAndRegion: "Spanish (Colombia)", region: "Colombia"},
    {languageAndRegionCode: "es-ES", regionCode: "ES", languageAndRegion: "Spanish (Spain)", region: "Spain"},
    {languageAndRegionCode: "es-MX", regionCode: "MX", languageAndRegion: "Spanish (Mexico)", region: "Mexico"},
    {languageAndRegionCode: "es-PE", regionCode: "PE", languageAndRegion: "Spanish (Peru)", region: "Peru"},
    {languageAndRegionCode: "et-EE", regionCode: "EE", languageAndRegion: "Estonian (Estonia)", region: "Estonia"},
    {languageAndRegionCode: "eu-ES", regionCode: "ES", languageAndRegion: "Basque (Spain)", region: "Spain"},
    {languageAndRegionCode: "fa-IR", regionCode: "IR", languageAndRegion: "Persian (Iran)", region: "Iran"},
    {languageAndRegionCode: "fi-FI", regionCode: "FI", languageAndRegion: "Finnish (Finland)", region: "Finland"},
    {languageAndRegionCode: "fr-BE", regionCode: "BE", languageAndRegion: "French (Belgium)", region: "Belgium"},
    {languageAndRegionCode: "fr-CA", regionCode: "CA", languageAndRegion: "French (Canada)", region: "Canada"},
    {languageAndRegionCode: "fr-CH", regionCode: "CH", languageAndRegion: "French (Switzerland)", region: "Switzerland"},
    {languageAndRegionCode: "fr-FR", regionCode: "FR", languageAndRegion: "French (France)", region: "France"},
    {languageAndRegionCode: "ga-IE", regionCode: "IE", languageAndRegion: "Irish (Ireland)", region: "Ireland"},
    {languageAndRegionCode: "gl-ES", regionCode: "ES", languageAndRegion: "Galician (Spain)", region: "Spain"},
    {languageAndRegionCode: "gu-IN", regionCode: "IN", languageAndRegion: "Gujarati (India)", region: "India"},
    {languageAndRegionCode: "he-IL", regionCode: "IL", languageAndRegion: "Hebrew (Israel)", region: "Israel"},
    {languageAndRegionCode: "hi-IN", regionCode: "IN", languageAndRegion: "Hindi (India)", region: "India"},
    {languageAndRegionCode: "hr-HR", regionCode: "HR", languageAndRegion: "Croatian (Croatia)", region: "Croatia"},
    {languageAndRegionCode: "hu-HU", regionCode: "HU", languageAndRegion: "Hungarian (Hungary)", region: "Hungary"},
    {languageAndRegionCode: "hy-AM", regionCode: "AM", languageAndRegion: "Armenian (Armenia)", region: "Armenia"},
    {languageAndRegionCode: "id-ID", regionCode: "ID", languageAndRegion: "Indonesian (Indonesia)", region: "Indonesia"},
    {languageAndRegionCode: "is-IS", regionCode: "IS", languageAndRegion: "Icelandic (Iceland)", region: "Iceland"},
    {languageAndRegionCode: "it-CH", regionCode: "CH", languageAndRegion: "Italian (Switzerland)", region: "Switzerland"},
    {languageAndRegionCode: "it-IT", regionCode: "IT", languageAndRegion: "Italian (Italy)", region: "Italy"},
    {languageAndRegionCode: "ja-JP", regionCode: "JP", languageAndRegion: "Japanese (Japan)", region: "Japan"},
    {languageAndRegionCode: "jv-ID", regionCode: "ID", languageAndRegion: "Javanese (Indonesia)", region: "Indonesia"},
    {languageAndRegionCode: "ka-GE", regionCode: "GE", languageAndRegion: "Georgian (Georgia)", region: "Georgia"},
    {languageAndRegionCode: "kk-KZ", regionCode: "KZ", languageAndRegion: "Kazakh (Kazakhstan)", region: "Kazakhstan"},
    {languageAndRegionCode: "km-KH", regionCode: "KH", languageAndRegion: "Khmer (Cambodia)", region: "Cambodia"},
    {languageAndRegionCode: "kn-IN", regionCode: "IN", languageAndRegion: "Kannada (India)", region: "India"},
    {languageAndRegionCode: "ko-KR", regionCode: "KR", languageAndRegion: "Korean (South Korea)", region: "South Korea"},
    {languageAndRegionCode: "ku-TR", regionCode: "TR", languageAndRegion: "Kurdish (Turkey)", region: "Turkey"},
    {languageAndRegionCode: "ky-KG", regionCode: "KG", languageAndRegion: "Kyrgyz (Kyrgyzstan)", region: "Kyrgyzstan"},
    {languageAndRegionCode: "la-VA", regionCode: "VA", languageAndRegion: "Latin (Vatican)", region: "Vatican"},
    {languageAndRegionCode: "lb-LU", regionCode: "LU", languageAndRegion: "Luxembourgish (Luxembourg)", region: "Luxembourg"},
    {languageAndRegionCode: "lo-LA", regionCode: "LA", languageAndRegion: "Lao (Laos)", region: "Laos"},
    {languageAndRegionCode: "lt-LT", regionCode: "LT", languageAndRegion: "Lithuanian (Lithuania)", region: "Lithuania"},
    {languageAndRegionCode: "lv-LV", regionCode: "LV", languageAndRegion: "Latvian (Latvia)", region: "Latvia"},
    {languageAndRegionCode: "mg-MG", regionCode: "MG", languageAndRegion: "Malagasy (Madagascar)", region: "Madagascar"},
    {languageAndRegionCode: "mk-MK", regionCode: "MK", languageAndRegion: "Macedonian (North Macedonia)", region: "North Macedonia"},
    {languageAndRegionCode: "ml-IN", regionCode: "IN", languageAndRegion: "Malayalam (India)", region: "India"},
    {languageAndRegionCode: "mn-MN", regionCode: "MN", languageAndRegion: "Mongolian (Mongolia)", region: "Mongolia"},
    {languageAndRegionCode: "mr-IN", regionCode: "IN", languageAndRegion: "Marathi (India)", region: "India"},
    {languageAndRegionCode: "ms-MY", regionCode: "MY", languageAndRegion: "Malay (Malaysia)", region: "Malaysia"},
    {languageAndRegionCode: "mt-MT", regionCode: "MT", languageAndRegion: "Maltese (Malta)", region: "Malta"},
    {languageAndRegionCode: "my-MM", regionCode: "MM", languageAndRegion: "Burmese (Myanmar)", region: "Myanmar"},
    {languageAndRegionCode: "nb-NO", regionCode: "NO", languageAndRegion: "Norwegian Bokmål (Norway)", region: "Norway"},
    {languageAndRegionCode: "ne-NP", regionCode: "NP", languageAndRegion: "Nepali (Nepal)", region: "Nepal"},
    {languageAndRegionCode: "nl-BE", regionCode: "BE", languageAndRegion: "Dutch (Belgium)", region: "Belgium"},
    {languageAndRegionCode: "nl-NL", regionCode: "NL", languageAndRegion: "Dutch (Netherlands)", region: "Netherlands"},
    {languageAndRegionCode: "nn-NO", regionCode: "NO", languageAndRegion: "Norwegian Nynorsk (Norway)", region: "Norway"},
    {languageAndRegionCode: "or-IN", regionCode: "IN", languageAndRegion: "Odia (India)", region: "India"},
    {languageAndRegionCode: "pa-IN", regionCode: "IN", languageAndRegion: "Punjabi (India)", region: "India"},
    {languageAndRegionCode: "pl-PL", regionCode: "PL", languageAndRegion: "Polish (Poland)", region: "Poland"},
    {languageAndRegionCode: "ps-AF", regionCode: "AF", languageAndRegion: "Pashto (Afghanistan)", region: "Afghanistan"},
    {languageAndRegionCode: "pt-BR", regionCode: "BR", languageAndRegion: "Portuguese (Brazil)", region: "Brazil"},
    {languageAndRegionCode: "pt-PT", regionCode: "PT", languageAndRegion: "Portuguese (Portugal)", region: "Portugal"},
    {languageAndRegionCode: "ro-RO", regionCode: "RO", languageAndRegion: "Romanian (Romania)", region: "Romania"},
    {languageAndRegionCode: "ru-RU", regionCode: "RU", languageAndRegion: "Russian (Russia)", region: "Russia"},
    {languageAndRegionCode: "si-LK", regionCode: "LK", languageAndRegion: "Sinhala (Sri Lanka)", region: "Sri Lanka"},
    {languageAndRegionCode: "sk-SK", regionCode: "SK", languageAndRegion: "Slovak (Slovakia)", region: "Slovakia"},
    {languageAndRegionCode: "sl-SI", regionCode: "SI", languageAndRegion: "Slovenian (Slovenia)", region: "Slovenia"},
    {languageAndRegionCode: "sq-AL", regionCode: "AL", languageAndRegion: "Albanian (Albania)", region: "Albania"},
    {languageAndRegionCode: "sr-RS", regionCode: "RS", languageAndRegion: "Serbian (Serbia)", region: "Serbia"},
    {languageAndRegionCode: "sv-SE", regionCode: "SE", languageAndRegion: "Swedish (Sweden)", region: "Sweden"},
    {languageAndRegionCode: "sw-KE", regionCode: "KE", languageAndRegion: "Swahili (Kenya)", region: "Kenya"},
    {languageAndRegionCode: "ta-IN", regionCode: "IN", languageAndRegion: "Tamil (India)", region: "India"},
    {languageAndRegionCode: "te-IN", regionCode: "IN", languageAndRegion: "Telugu (India)", region: "India"},
    {languageAndRegionCode: "th-TH", regionCode: "TH", languageAndRegion: "Thai (Thailand)", region: "Thailand"},
    {languageAndRegionCode: "tl-PH", regionCode: "PH", languageAndRegion: "Tagalog (Philippines)", region: "Philippines"},
    {languageAndRegionCode: "tr-TR", regionCode: "TR", languageAndRegion: "Turkish (Turkey)", region: "Turkey"},
    {languageAndRegionCode: "ug-CN", regionCode: "CN", languageAndRegion: "Uyghur (China)", region: "China"},
    {languageAndRegionCode: "uk-UA", regionCode: "UA", languageAndRegion: "Ukrainian (Ukraine)", region: "Ukraine"},
    {languageAndRegionCode: "ur-PK", regionCode: "PK", languageAndRegion: "Urdu (Pakistan)", region: "Pakistan"},
    {languageAndRegionCode: "uz-UZ", regionCode: "UZ", languageAndRegion: "Uzbek (Uzbekistan)", region: "Uzbekistan"},
    {languageAndRegionCode: "vi-VN", regionCode: "VN", languageAndRegion: "Vietnamese (Vietnam)", region: "Vietnam"},
    {languageAndRegionCode: "zh-CN", regionCode: "CN", languageAndRegion: "Chinese (China)", region: "China"},
    {languageAndRegionCode: "zh-HK", regionCode: "HK", languageAndRegion: "Chinese (Hong Kong)", region: "Hong Kong"},
    {languageAndRegionCode: "zh-TW", regionCode: "TW", languageAndRegion: "Chinese (Taiwan)", region: "Taiwan"},
    {languageAndRegionCode: "zu-ZA", regionCode: "ZA", languageAndRegion: "Zulu (South Africa)", region: "South Africa"},
];

export interface LanguageAndRegion {
    languageAndRegionCode: string
    regionCode: string
    languageAndRegion: string
    region: string
}