export const provider: Provider[] = [
  {name: 'NETFLIX', readableName: 'Netflix', logoPath: '/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg', id: 8, mainProvider: true},
  {name: 'AMAZON_PRIME_VIDEO', readableName: 'Amazon Prime Video', logoPath: '/dQeAar5H991VYporEjUspolDarG.jpg', id: 9, mainProvider: true},
  {name: 'DISNEY_PLUS', readableName: 'Disney+', logoPath: '/97yvRBw1GzX7fXprcF80er19ot.jpg', id: 337, mainProvider: true},
  {name: 'APPLE_TV_PLUS', readableName: 'Apple TV+', logoPath: '/2E03IAZsX4ZaUqM7tXlctEPMGWS.jpg', id: 350, mainProvider: true},
  {name: 'APPLE_TV', readableName: 'Apple TV', logoPath: '/9ghgSC0MA082EL6HLCW3GalykFD.jpg', id: 2, mainProvider: false},
  {name: 'WOW', readableName: 'WOW', logoPath: '/9r5zFWuYnwjzO1JrNjSbLQwUc3P.jpg', id: 30, mainProvider: true},
  {name: 'CRUNCHYROLL', readableName: 'Crunchyroll', logoPath: '/mXeC4TrcgdU6ltE9bCBCEORwSQR.jpg', id: 283, mainProvider: false},
  {name: 'SKY_GO', readableName: 'Sky Go', logoPath: '/1UrT2H9x6DuQ9ytNhsSCUFtTUwS.jpg', id: 29, mainProvider: false},
  {name: 'AMAZON_VIDEO', readableName: 'Amazon Video', logoPath: '/seGSXajazLMCKGB5hnRCidtjay1.jpg', id: 10, mainProvider: false},
  {name: 'PARAMOUNT_PLUS', readableName: 'Paramount+', logoPath: '/h5DcR0J2EESLitnhR8xLG1QymTE.jpg', id: 531, mainProvider: true},
  {name: 'GOOGLE_PLAY_MOVIES', readableName: 'Google Play Movies', logoPath: '/8z7rC8uIDaTM91X0ZfkRf04ydj2.jpg', id: 3, mainProvider: true},
  {name: 'JOYN', readableName: 'Joyn', logoPath: '/tDnDBkSLLLQgFb03J9ttQhZQxZs.jpg', id: 304, mainProvider: true},
  {name: 'YOUTUBE', readableName: 'YouTube', logoPath: '/pTnn5JwWr4p3pG8H6VrpiQo7Vs0.jpg', id: 192, mainProvider: true},
  {name: 'SKY_STORE', readableName: 'Sky Store', logoPath: '/6AKbY2ayaEuH4zKg2prqoVQ9iaY.jpg', id: 130, mainProvider: false},
  {name: 'RAKUTEN_TV', readableName: 'Rakuten TV', logoPath: '/bZvc9dXrXNly7cA0V4D9pR8yJwm.jpg', id: 35, mainProvider: false},
  {name: 'RTL_PLUS', readableName: 'RTL+', logoPath: '/jmR0t1kjzHcyV7raynzMbF87J9d.jpg', id: 298, mainProvider: true},
  {name: 'MAXDOME_STORE', readableName: 'maxdome Store', logoPath: '/cBN4jd4wPq6on0kESiTlevqvlnL.jpg', id: 20, mainProvider: false},
  {name: 'VIDEOBUSTER', readableName: 'Videobuster', logoPath: '/82hFfWsPYtyskBrnkL8Y36vHcVf.jpg', id: 133, mainProvider: false},
  {name: 'YOUTUBE_PREMIUM', readableName: 'YouTube Premium', logoPath: '/rMb93u1tBeErSYLv79zSTR07UdO.jpg', id: 188, mainProvider: false},
  {name: 'ALLESKINO', readableName: 'Alleskino', logoPath: '/m0zZQjEHcp8np3lkMdMZE9QRwjA.jpg', id: 33, mainProvider: false},
  {name: 'ARTE', readableName: 'Arte', logoPath: '/vPZrjHe7wvALuwJEXT2kwYLi0gV.jpg', id: 234, mainProvider: false},
  {name: 'MAGENTATV', readableName: 'MagentaTV', logoPath: '/lrEigPPAhggq02q53uM8vdWAIUX.jpg', id: 178, mainProvider: true},
  {name: 'ARD_MEDIATHEK', readableName: 'ARD Mediathek', logoPath: '/avItehPq07h5nKCJgwNTxl6OD0y.jpg', id: 219, mainProvider: true},
  {name: 'MUBI', readableName: 'MUBI', logoPath: '/fj9Y8iIMFUC6952HwxbGixTQPb7.jpg', id: 11, mainProvider: false},
  {name: 'NETZKINO', readableName: 'Netzkino', logoPath: '/4bKgwiotEIN6wiZNQhQfjp7qPCk.jpg', id: 28, mainProvider: false},
  {name: 'NETFLIX_KIDS', readableName: 'Netflix Kids', logoPath: '/kwVegvKCinXTPuzZmYT1J3i1HJz.jpg', id: 175, mainProvider: false},
  {name: 'GUIDEDOC', readableName: 'GuideDoc', logoPath: '/eKVmLFHW5PeNhuR7Nedd8OIxW2M.jpg', id: 100, mainProvider: false},
  {name: 'MICROSOFT_STORE', readableName: 'Microsoft Store', logoPath: '/5vfrJQgNe9UnHVgVNAwZTy0Jo9o.jpg', id: 68, mainProvider: false},
  {name: 'ZDF_HERZKINO_AMAZON_CHANNEL', readableName: 'ZDF Herzkino Amazon Channel', logoPath: '/FtIkEXYkqTxKwCwLK79yKJW8i7.jpg', id: 286, mainProvider: false},
  {name: 'BBC_PLAYER_AMAZON_CHANNEL', readableName: 'BBC Player Amazon Channel', logoPath: '/jhhFTFVWjKVi2JjDYoqoI4dHsmL.jpg', id: 285, mainProvider: false},
  {name: 'MUBI_AMAZON_CHANNEL', readableName: 'MUBI Amazon Channel', logoPath: '/a4IDLKjvP5gvq7tNlg2Xw5YyEkI.jpg', id: 201, mainProvider: false},
  {name: 'FILMTASTIC_AMAZON_CHANNEL', readableName: 'Filmtastic Amazon Channel', logoPath: '/ni0t0Bj4HRAQ9f6zSv1Bl9MDjLK.jpg', id: 334, mainProvider: false},
  {name: 'WEDOTV', readableName: 'wedotv', logoPath: '/jAwT86Q0H9U8RESR3zR2FVKe83D.jpg', id: 392, mainProvider: false},
  {name: 'BLUTV', readableName: 'blutv', logoPath: '/dqRpKX6vcos334v9huMpNPKHlD8.jpg', id: 341, mainProvider: false},
  {name: 'KINO_ON_DEMAND', readableName: 'Kino on Demand', logoPath: '/yTwdlHzReo6l9HLWrZqEaEUECBt.jpg', id: 349, mainProvider: false},
  {name: 'RAKUTEN_VIKI', readableName: 'Rakuten Viki', logoPath: '/5L2bwr9DhUg28oSMEPRCNwB2y7B.jpg', id: 344, mainProvider: false},
  {name: 'JOYN_PLUS', readableName: 'Joyn+', logoPath: '/5aHLriu21FRDGlxY5zbzyEuoSvA.jpg', id: 421, mainProvider: true},
  {name: 'CONTV', readableName: 'CONtv', logoPath: '/RnSjeA2dgmKNLlFV3JE8cmPyLS.jpg', id: 428, mainProvider: false},
  {name: 'CURIOSITY_STREAM', readableName: 'Curiosity Stream', logoPath: '/oR1aNm1Qu9jQBkW4VrGPWhqbC3P.jpg', id: 190, mainProvider: false},
  {name: 'DOCSVILLE', readableName: 'DOCSVILLE', logoPath: '/5zqbck5mo8PuVbGu2ngBUdn5Yga.jpg', id: 475, mainProvider: false},
  {name: 'HOME_OF_HORROR', readableName: 'Home of Horror', logoPath: '/ntvIffmJe7ZO1SSobwSx8ABAZFG.jpg', id: 479, mainProvider: false},
  {name: 'FILMTASTIC', readableName: 'Filmtastic', logoPath: '/eptSSZPhXJllBI8QywFDmgOMNkU.jpg', id: 480, mainProvider: false},
  {name: 'ARTHOUSECNMA', readableName: 'ArthouseCNMA', logoPath: '/eBt8WXNGuJGBgQ28W88Y3eTAWsD.jpg', id: 481, mainProvider: false},
  {name: 'POPCORNTIMES', readableName: 'Popcorntimes', logoPath: '/3kmmwlTET45ryW7azWfFJ0Piwll.jpg', id: 522, mainProvider: false},
  {name: 'SPAMFLIX', readableName: 'Spamflix', logoPath: '/k2YgZyxij5RcnS1qqUYEUrJB4oQ.jpg', id: 521, mainProvider: false},
  {name: 'LACINETEK', readableName: 'LaCinetek', logoPath: '/1syoSwH2yIskHUqeOiK9re8AMJC.jpg', id: 310, mainProvider: false},
  {name: 'AMAZON_ARTHAUS_CHANNEL', readableName: 'Amazon Arthaus Channel', logoPath: '/9MABvFilVMUAV86vLUgBgeM5LQQ.jpg', id: 533, mainProvider: false},
  {name: 'ARTHOUSE_CNMA_AMAZON_CHANNEL', readableName: 'Arthouse CNMA Amazon Channel', logoPath: '/tnQ5PGryncrVxE9bK6nxif82wtd.jpg', id: 687, mainProvider: false},
  {name: 'ZDF', readableName: 'ZDF Mediathek', logoPath: '/ugus0p8BGGhE8sxhwAjJz2o8jyy.jpg', id: 537, mainProvider: true},
  {name: 'PLEX', readableName: 'Plex', logoPath: '/vLZKlXUNDcZR7ilvfY9Wr9k80FZ.jpg', id: 538, mainProvider: false},
  {name: 'WOW_PRESENTS_PLUS', readableName: 'WOW Presents+', logoPath: '/6dET59jNU0ADysghEjl8Unuc7Ca.jpg', id: 546, mainProvider: false},
  {name: 'FILMFRIEND', readableName: 'filmfriend', logoPath: '/zXu75uIAMgdblYvFFPzoIHmQhxa.jpg', id: 542, mainProvider: false},
  {name: 'MAGELLAN_TV', readableName: 'Magellan TV', logoPath: '/mSH24WQcRDJ2fsL5iucXqqRnSRb.jpg', id: 551, mainProvider: false},
  {name: 'BROADWAYHD', readableName: 'BroadwayHD', logoPath: '/6IYZ4NjwPikxN7J9cfSmuyeHeMm.jpg', id: 554, mainProvider: false},
  {name: 'FILMZIE', readableName: 'Filmzie', logoPath: '/eUBxtrqO26wAJfYOZJOzhQEo3mm.jpg', id: 559, mainProvider: false},
  {name: 'MOVIESAINTS', readableName: 'MovieSaints', logoPath: '/9vMVMnVnWwxt0TkCazKLYW1zuqY.jpg', id: 562, mainProvider: false},
  {name: 'DEKKOO', readableName: 'Dekkoo', logoPath: '/x6nRFzF32hCzMHaVM4RHRo7lsgS.jpg', id: 444, mainProvider: false},
  {name: 'DOGWOOF_ON_DEMAND', readableName: 'Dogwoof On Demand', logoPath: '/7m26fd7Lqw8l779ZRMHHADAcslm.jpg', id: 536, mainProvider: false},
  {name: 'TRUE_STORY', readableName: 'True Story', logoPath: '/aRPDQvVcpeY07sjI6lAALMCL0ti.jpg', id: 567, mainProvider: false},
  {name: 'DOCALLIANCE_FILMS', readableName: 'DocAlliance Films', logoPath: '/vbXJBJVv3u3YWt6ml0l0ldDblXT.jpg', id: 569, mainProvider: false},
  {name: 'HOICHOI', readableName: 'Hoichoi', logoPath: '/u7dwMceEbjxd1N3TLEUBILSK2x6.jpg', id: 315, mainProvider: false},
  {name: 'PLUTO_TV', readableName: 'Pluto TV', logoPath: '/dB8G41Q6tSL5NBisrIeqByfepBc.jpg', id: 300, mainProvider: false},
  {name: 'FILMLEGENDEN_AMAZON_CHANNEL', readableName: 'Filmlegenden Amazon Channel', logoPath: '/iM7Ed1d7mYT3DQWSqLoW3tIN4uS.jpg', id: 678, mainProvider: false},
  {name: 'EVENTIVE', readableName: 'Eventive', logoPath: '/fwx5Ed64TkfWiRH1SOSkc4781Ts.jpg', id: 677, mainProvider: false},
  {name: 'CINEMA_OF_HEARTS_AMAZON_CHANNEL', readableName: 'Cinema of Hearts Amazon Channel', logoPath: '/coWnECpOyKLWMTSlXkfT2PhLs9E.jpg', id: 679, mainProvider: false},
  {name: 'HOME_OF_HORROR_AMAZON_CHANNEL', readableName: 'Home of Horror Amazon Channel', logoPath: '/7Zy6GqC8lQEvfBlWC1bJcaJzPRd.jpg', id: 686, mainProvider: false},
  {name: 'BLOODY_MOVIES_AMAZON_CHANNEL', readableName: 'Bloody Movies Amazon Channel', logoPath: '/jG5tKt6JoHsYRoUq6Wg8i9QuHt2.jpg', id: 680, mainProvider: false},
  {name: 'FILM_TOTAL_AMAZON_CHANNEL', readableName: 'Film Total Amazon Channel', logoPath: '/3fhcb4cThixkfNpOudnpLcosTCA.jpg', id: 681, mainProvider: false},
  {name: 'TURK_ON_VIDEO_AMAZON_CHANNEL', readableName: 'Turk On Video Amazon Channel', logoPath: '/9aLd9gAK6xHtWK2tXDYq1fOqzJA.jpg', id: 693, mainProvider: false},
  {name: 'CULTPIX', readableName: 'Cultpix', logoPath: '/uauVx3dGWt0GICqdMCBYJObd3Mo.jpg', id: 692, mainProvider: false},
  {name: 'FILMBOX_PLUS', readableName: 'FilmBox+', logoPath: '/fbveJTcro9Xw2KuPIIoPPePHiwy.jpg', id: 701, mainProvider: false},
  {name: 'AVA_VOBB', readableName: 'AVA VOBB', logoPath: '/nJlTOUfDEUD6fQLopWBnUNzo2NA.jpg', id: 1722, mainProvider: false},
  {name: 'AVA_HBZ', readableName: 'AVA HBZ', logoPath: '/p1mlqlIOtPPZf7lckxX3XLAm2ia.jpg', id: 1723, mainProvider: false},
  {name: 'BLUTV_AMAZON_CHANNEL', readableName: 'BluTV Amazon Channel', logoPath: '/AvUM6aAqYh7JxUokb5T5ERn3KMs.jpg', id: 1707, mainProvider: false},
  {name: 'COMEDY_CENTRAL_PLUS_AMAZON_CHANNEL', readableName: 'Comedy Central Plus Amazon Channel', logoPath: '/eMoqH13BYzIC1wDlhONhHfDM3DN.jpg', id: 1706, mainProvider: false},
  {name: 'GRJNGO_AMAZON_CHANNEL', readableName: 'GRJNGO Amazon Channel', logoPath: '/cYzZyot2IuGUYUXLvw6BMBT6v9p.jpg', id: 1709, mainProvider: false},
  {name: 'MTV_PLUS_AMAZON_CHANNEL', readableName: 'MTV Plus Amazon Channel', logoPath: '/g06QZd5k4bjDEcZ3J97jb3rNlfB.jpg', id: 1711, mainProvider: false},
  {name: 'SILVERLINE_AMAZON_CHANNEL', readableName: 'Silverline Amazon Channel', logoPath: '/xXN970tHrMfL7BQUTVSu96IY9gs.jpg', id: 1713, mainProvider: false},
  {name: 'RTL_PASSION_AMAZON_CHANNEL', readableName: 'RTL Passion Amazon Channel', logoPath: '/gHBdFYhxdeLHl8jimTDwA1bFv01.jpg', id: 1712, mainProvider: false},
  {name: 'FREEVEE', readableName: 'Freevee', logoPath: '/4VOCKZGiAtXMtoDyOrvHAN33uc2.jpg', id: 613, mainProvider: true},
  {name: 'SOONER_AMAZON_CHANNEL', readableName: 'Sooner Amazon Channel', logoPath: '/6WQqJyaFd0fmLLE6WIjFQyEyAFj.jpg', id: 1757, mainProvider: false},
  {name: 'YORCK_ON_DEMAND', readableName: 'Yorck on Demand', logoPath: '/zHjoZOQ2DOlu2HCZH18bzQYGc3t.jpg', id: 1764, mainProvider: false},
  {name: 'TAKFLIX', readableName: 'Takflix', logoPath: '/ed0vz5bryWIhQB5sHiuGvHKnHHn.jpg', id: 1771, mainProvider: false},
  {name: 'LOVE_AND_PASSION_AMAZON_CHANNEL', readableName: 'Love and Passion Amazon Channel', logoPath: '/rYszOzWFzq7xPffwJ7XN5rJRI7u.jpg', id: 1788, mainProvider: false},
  {name: 'SUN_NXT', readableName: 'Sun Nxt', logoPath: '/6KEQzITx2RrCAQt5Nw9WrL1OI8z.jpg', id: 309, mainProvider: false},
  {name: 'CLASSIX', readableName: 'Classix', logoPath: '/uFjAjvrKMII0H766QzyHDNkZdKX.jpg', id: 445, mainProvider: false},
  {name: 'NETFLIX_BASIC_WITH_ADS', readableName: 'Netflix basic with Ads', logoPath: '/kICQccvOh8AIBMHGkBXJ047xeHN.jpg', id: 1796, mainProvider: false},
  {name: 'STUDIOCANAL_PRESENTS_MOVIECULT_AMAZON_CHANNEL', readableName: 'Studiocanal Presents MOVIECULT Amazon Channel', logoPath: '/3VYyCBiG2WTCZ2tGzTkWvoXTeqi.jpg', id: 1805, mainProvider: false},
  {name: 'STUDIOCANAL_PRESENTS_ALLSTARS_AMAZON_CHANNEL', readableName: 'Studiocanal Presents ALLSTARS Amazon Channel', logoPath: '/tHX1KI8VdAzKWMxSgPKqKfHcxFA.jpg', id: 1806, mainProvider: false},
  {name: 'DISCOVERY_PLUS_AMAZON_CHANNEL', readableName: 'Discovery+ Amazon Channel', logoPath: '/lgudHqEtTOzkMWlpTjU1oUyoUSZ.jpg', id: 584, mainProvider: false},
  {name: 'PARAMOUNT_PLUS_AMAZON_CHANNEL', readableName: 'Paramount+ Amazon Channel', logoPath: '/hExO4PtimLIYn3kBOrzsejNv7cT.jpg', id: 582, mainProvider: false},
  {name: 'BEHIND_THE_TREE', readableName: 'Behind the Tree', logoPath: '/fxYgfnsrUWa7e9aNr3j3RERpm66.jpg', id: 1829, mainProvider: false},
  {name: 'FILMINGO', readableName: 'filmingo', logoPath: '/704tOH9qi7y7DDl1CmzDCAI0dcQ.jpg', id: 1756, mainProvider: false},
  {name: 'PARAMOUNT_PLUS_APPLE_TV_CHANNEL_', readableName: 'Paramount Plus Apple TV Channel ', logoPath: '/tJqmTmQ8jp9WfyaZfApHK8lSywA.jpg', id: 1853, mainProvider: false},
  {name: 'OUTTV_AMAZON_CHANNEL', readableName: 'OUTtv Amazon Channel', logoPath: '/d0KmcInHpiF44ahOLrXCQATEFmD.jpg', id: 607, mainProvider: false},
  {name: 'ALLESKINO_AMAZON_CHANNEL', readableName: 'alleskino Amazon Channel', logoPath: '/s7ZjSKXOtjKBb7hAzBm3b0iY0SG.jpg', id: 1891, mainProvider: false},
  {name: 'RTL_CRIME_AMAZON_CHANNEL', readableName: 'RTL Crime Amazon Channel', logoPath: '/5Qe65kN95Z0CytOaG3I8bytdW7A.jpg', id: 1892, mainProvider: false},
  {name: 'ARD_PLUS', readableName: 'ARD+', logoPath: '/qTybjmHLNcXZExZLBnm4muVCDzP.jpg', id: 1902, mainProvider: false},
  {name: 'MOVIEDOME_PLUS_AMAZON_CHANNEL', readableName: 'Moviedome Plus Amazon Channel', logoPath: '/9NYihXY9biyXFJSZQq5HIGu1n8B.jpg', id: 706, mainProvider: false},
  {name: 'ANIVERSE_AMAZON_CHANNEL', readableName: 'Aniverse Amazon Channel', logoPath: '/a2wCZ9ultzAbjAaG6JMiCFJoy9s.jpg', id: 707, mainProvider: false},
  {name: 'SUPERFRESH_AMAZON_CHANNEL', readableName: 'Superfresh Amazon Channel', logoPath: '/9T5H28SXBkzmnZYy2iRfI7GzwLL.jpg', id: 708, mainProvider: false},
  {name: 'AD_TV', readableName: 'AD tv', logoPath: '/mK8nfCXfwoAa6cAkHUSKCkLEIKK.jpg', id: 1958, mainProvider: false},
  {name: 'SHAHID_VIP', readableName: 'Shahid VIP', logoPath: '/7qZED0kLBtiV8mLRNBtW4PQCAqW.jpg', id: 1715, mainProvider: false},
  {name: 'FULL_MOON_AMAZON_CHANNEL', readableName: 'Full Moon Amazon Channel', logoPath: '/xIu1EW7y2EC7RD3Wqe0Ogi5NAuo.jpg', id: 597, mainProvider: false},
  {name: 'ZDF_SELECT_AMAZON_CHANNEL_', readableName: 'ZDF Select Amazon Channel ', logoPath: '/mmDWKHiDLmHDo2OWnduQuI1T4bh.jpg', id: 1989, mainProvider: false},
  {name: 'VIDEOLOAD', readableName: 'Videoload', logoPath: '/dKh2TJ9lTWV0UIcDQGMnMyQ8AIN.jpg', id: 1993, mainProvider: false},
  {name: 'TELE_5', readableName: 'TELE 5', logoPath: '/a1zZJiOid4gG27xJtkcDaSVrQdb.jpg', id: 1994, mainProvider: false},
  {name: 'ARD_PLUS_APPLE_TV_CHANNEL', readableName: 'ARD Plus Apple TV channel', logoPath: '/9jxvmD363A04nuMw9jgyLzeDB3J.jpg', id: 2037, mainProvider: false},
  {name: 'ARTHAUS_PLUS_APPLE_TV_CHANNEL', readableName: 'Arthaus+ Apple TV channel', logoPath: '/as1NArQkfAnptYQP3VS03GOJPdm.jpg', id: 2038, mainProvider: false},
  {name: 'WEDO_TV', readableName: 'Wedo TV', logoPath: '/ptSF973yIl90KwhEmNWDvN1nhan.jpg', id: 2076, mainProvider: false},
  {name: 'KIKA', readableName: 'KiKA', logoPath: '/5JkLub6H7HsWyLHbitnuXTzXmlJ.jpg', id: 2081, mainProvider: false},
  {name: 'SOONER', readableName: 'Sooner', logoPath: '/jzWBemDX69VRYhudQA44IESMxQ1.jpg', id: 389, mainProvider: false},
  {name: 'CHILI', readableName: 'Chili', logoPath: '/rVEXDsaHzpwK1YhXEZrsmvfpdOR.jpg', id: 40, mainProvider: false},
  {name: 'AMAZON_PRIME_VIDEO_WITH_ADS', readableName: 'Amazon Prime Video with Ads', logoPath: '/p4TlGiuRoH9sDZeppPJeMhizs26.jpg', id: 2100, mainProvider: false},
  {name: 'ANIMATION_DIGITAL_NETWORK', readableName: 'Animation Digital Network', logoPath: '/w86FOwg0bbgUSHWWnjOTuEjsUvq.jpg', id: 415, mainProvider: false},
  {name: 'AXN_BLACK_AMAZON_CHANNEL', readableName: 'AXN Black Amazon Channel', logoPath: '/bh0e83QEvjzttsj8FJcQaYxPR43.jpg', id: 2134, mainProvider: false},
  {name: 'ARTHAUS_PLUS', readableName: 'Arthaus+', logoPath: '/inTlUMvnQrtCee5fnO4J45SuIwH.jpg', id: 2137, mainProvider: false},
  {name: 'MGM_PLUS_AMAZON_CHANNEL', readableName: 'MGM Plus Amazon Channel', logoPath: '/efu1Cqc63XrPBoreYnf2mn0Nizj.jpg', id: 2141, mainProvider: false},
  {name: 'ANIME_DIGITAL_NETWORK_AMAZON_CHANNEL', readableName: 'Anime Digital Network Amazon Channel', logoPath: '/h5QpXIpSnvrPFnOLRXV83CtVHQH.jpg', id: 2173, mainProvider: false}
];

export interface Provider {
    name: string
    readableName: string
    logoPath: string
    id: number
    mainProvider: boolean
}
